CREATE TABLE "members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar NOT NULL ,
  "password" varchar NOT NULL,
  "date_registered" integer NOT NULL
);

CREATE TABLE "decks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "created_by" integer NOT NULL,
  "deck_name" varchar NOT NULL,
  "views" integer DEFAULT 0 NOT NULL,
  "date_created" integer NOT NULL
);

CREATE TABLE "cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "deck_id" integer NOT NULL,
  "api_card_id" varchar NOT NULL,
  "card_name" varchar NOT NULL,
  "artwork_url" varchar NOT NULL
);

CREATE TABLE "search_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "input" varchar NOT NULL,
  "date" integer NOT NULL
);

ALTER TABLE "decks" ADD FOREIGN KEY ("created_by") REFERENCES "members" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("deck_id") REFERENCES "decks" ("id") ON DELETE CASCADE;

ALTER TABLE "members" ADD CONSTRAINT UNIQUE "username";